/* Demonstração isolada: dados em memória; nenhuma chamada de rede ou autenticação real. */
"use strict";
const isChecklist = document.body.dataset.project === "checklist";
const app = document.getElementById("app");
const modal = document.getElementById("dialog");
const escapeHtml = value => String(value).replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money = cents => new Intl.NumberFormat("pt-BR", {style:"currency",currency:"BRL"}).format(cents / 100);
const clients = [
  {id:1,name:"Cliente Alfa (demo)",bread:650,sweet:820},
  {id:2,name:"Cliente Beta (demo)",bread:680,sweet:850},
  {id:3,name:"Cliente Gama (demo)",bread:620,sweet:790},
  {id:4,name:"Cliente Delta (demo)",bread:700,sweet:900}
];
const initialDeliveries = [
  {id:101,client:1,cents:32500,driver:"Ana · fictícia",date:"21/09/2026",due:"21/09/2026",kind:"Boleto",paid:false},
  {id:102,client:2,cents:40800,driver:"Bruno · fictício",date:"21/09/2026",due:"22/09/2026",kind:"Dívida",paid:false},
  {id:103,client:3,cents:18600,driver:"Ana · fictícia",date:"20/09/2026",due:"21/09/2026",kind:"À vista",paid:true},
  {id:104,client:4,cents:28000,driver:"Bruno · fictício",date:"19/09/2026",due:"20/09/2026",kind:"Boleto",paid:false}
];
let deliveries = structuredClone(initialDeliveries);
let view = isChecklist ? "hoje" : "entregas";
let role = "admin", query = "", filter = "todos", demoDay = 21, offline = false, queued = 0;
let marks = {21:{1:"ok",2:"ok",3:"ok",4:"bad",5:null}};
let issues = {4:{open:true,openedDay:21,resolvedDay:null}};
const items = [
  ["Óleo","Nível pela vareta e validade da troca."],
  ["Água do reservatório","Nível, vazamentos e fechamento do reservatório."],
  ["Fluido e freio","Nível do fluido e acionamento do freio."],
  ["Sistema de refrigeração","Condições e funcionamento da refrigeração."],
  ["Pneus","Condições gerais e calibragem."]
];
const menus = isChecklist ? [["hoje","Inspeção de hoje"],["grade","Grade mensal"],["pendencias","Não conformidades"]] : [["entregas","Entregas"],["cobrancas","A cobrar"],["clientes","Clientes e preços"],["relatorios","Relatórios"]];
const cname = id => clients.find(c=>c.id === id).name;
const visibleDeliveries = () => deliveries.filter(d => role === "admin" || d.driver.startsWith("Ana"));
function notify(message){const node=document.getElementById("notice");node.textContent=message;clearTimeout(notify.timer);notify.timer=setTimeout(()=>node.textContent="",4500);}
function badge(d){return `<span class="status ${d.paid?"paid":""}">${d.paid?"Pago":"A cobrar"}</span>`;}
function openModal(title,body){modal.innerHTML=`<button class="close" data-action="close" aria-label="Fechar detalhes">×</button><span class="eyebrow">Demonstração</span><h2 id="dialog-title">${title}</h2>${body}`;modal.showModal();}
function top(title,subtitle,action=""){return `<div class="heading"><div><span class="eyebrow">${isChecklist?"Inspeção de frota":"Gestão de Entregas"}</span><h1>${title}</h1><p class="muted">${subtitle}</p></div>${action}</div>`;}
function stats(values){return `<section class="grid stats-grid">${values.map(([label,value,detail])=>`<div class="card"><div class="muted">${label}</div><div class="metric">${value}</div><small class="muted">${detail}</small></div>`).join("")}</section>`;}
function deliveryRows(rows){return rows.length?rows.map(d=>`<div class="row"><span class="round">${cname(d.client).slice(0,1)}</span><div class="grow"><h3>${escapeHtml(cname(d.client))}</h3><small>${d.date} · ${d.driver}</small></div><div class="amount">${money(d.cents)}<small>${badge(d)}</small></div><div class="actions"><button data-action="details" data-id="${d.id}">Ver detalhes</button></div></div>`).join(""):`<p class="empty">Nenhuma entrega corresponde aos filtros.</p>`;}
function filteredRows(){return visibleDeliveries().filter(d=>(view!=="cobrancas"||!d.paid)&&(filter==="todos"||(filter==="pago"?d.paid:!d.paid))&&cname(d.client).toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));}
function deliveryPage(){return top(view==="cobrancas"?"A cobrar":"Entregas",view==="cobrancas"?"Recebimentos organizados por cliente e data de cobrança.":"Notas e recebimentos, um registro de cada vez.",`<button class="primary" data-action="new">+ Nova entrega fictícia</button>`)+stats([["A cobrar",visibleDeliveries().filter(d=>!d.paid).length,"entregas pendentes"],["Hoje",visibleDeliveries().filter(d=>!d.paid&&d.due==="21/09/2026").length,"cobranças agendadas"],["Responsável",role==="admin"?"Equipe":"Ana",role==="admin"?"visualização administrativa":"perfil fictício"]])+`<section class="card"><div class="toolbar"><input id="search" aria-label="Pesquisar cliente" placeholder="Pesquisar cliente" value="${escapeHtml(query)}"><label>Situação<select id="filter"><option value="todos" ${filter==="todos"?"selected":""}>Todas</option><option value="aberto" ${filter==="aberto"?"selected":""}>A cobrar</option>${view==="entregas"?`<option value="pago" ${filter==="pago"?"selected":""}>Pago</option>`:""}</select></label></div><div id="rows">${deliveryRows(filteredRows())}</div></section>`;}
function clientsPage(){return top("Clientes e preços","Tabela própria de produtos para cada cliente fictício.")+`<section class="grid two">${clients.map(c=>`<article class="card"><span class="eyebrow">Cliente demonstrativo</span><h2>${c.name}</h2><table><thead><tr><th>Produto</th><th>Valor unitário</th></tr></thead><tbody><tr><td>Produto A</td><td>${money(c.bread)}</td></tr><tr><td>Produto B</td><td>${money(c.sweet)}</td></tr></tbody></table><div class="actions" style="margin-top:18px"><button data-action="history" data-id="${c.id}">Histórico de entregas</button></div></article>`).join("")}</section>`;}
function reportsPage(){const rows=visibleDeliveries();return top("Relatórios","Consulte cada entrega e acompanhe o trabalho da equipe.")+`<div class="split"><section class="card"><h2>Entregas por motorista</h2><p class="muted">Quantidade de registros fictícios, sem acumulados financeiros.</p>${["Ana · fictícia","Bruno · fictício"].map(name=>{const n=rows.filter(d=>d.driver===name).length;return `<div class="row"><div class="grow"><h3>${name}</h3><div class="bar"><span style="width:${n/Math.max(1,rows.length)*100}%"></span></div></div><strong>${n}</strong></div>`;}).join("")}</section><section class="card"><h2>Como consultar</h2><ol class="step-list"><li>Abra os detalhes de uma entrega.</li><li>Confira o cliente e a data de cobrança.</li><li>Veja a nota demonstrativa e simule o recebimento.</li></ol><span class="status neutral">Valores somente por registro</span></section></div><section class="card" style="margin-top:22px"><h2>Registros do relatório</h2>${deliveryRows(rows)}</section>`;}
function effective(n,day=demoDay){const issue=issues[n];if(issue&&day>=issue.openedDay&&(issue.open||(issue.resolvedDay!==null&&day<issue.resolvedDay)))return "bad";return marks[day]?.[n]||null;}
function inspectionPage(){const done=items.filter((_,i)=>effective(i+1)).length;return top("Inspeção de hoje",`Caminhão demonstrativo · DEM0A01 · ${demoDay}/09/2026`)+`<section class="card" style="margin-bottom:20px"><div class="row" style="padding-top:0"><div class="grow"><h2>Antes de sair para a rota</h2><p class="muted">${done} de 5 itens verificados · ${role==="admin"?"Administrador":"Inspetora Ana"} fictício</p></div><span class="status ${Object.values(issues).some(i=>i.open)?"issue":"ok"}">${Object.values(issues).some(i=>i.open)?"Há uma não conformidade":"Sem não conformidade aberta"}</span></div><div class="progress"><span style="width:${done*20}%"></span></div></section>${items.map(([title,desc],i)=>{const n=i+1,s=effective(n);return `<section class="card inspection"><span class="round">${n}</span><div><h3>${title}</h3><p>${desc}</p>${issues[n]?.open?`<span class="status issue">Não conformidade aberta · exige resolução</span>`:""}</div><div class="actions"><button data-action="mark" data-id="${n}" data-value="ok" aria-label="${title}: conforme" aria-pressed="${s==="ok"}" ${issues[n]?.open?"disabled":""}>✓ Conforme</button><button class="issue" data-action="mark" data-id="${n}" data-value="bad" aria-label="${title}: não conforme" aria-pressed="${s==="bad"}">! Não conforme</button></div></section>`;}).join("")}<div class="callout"><strong>A pendência continua no dia seguinte.</strong><p>Marcar os outros itens não resolve uma não conformidade. Essa ação cabe ao administrador.</p></div><section class="card simulation"><button data-action="next-day">Simular próximo dia</button><button data-action="offline">${offline?"Voltar ao modo conectado":"Simular sem sinal"}</button><span class="muted">${offline?`${queued} alterações na fila simulada`:"Modo conectado simulado"} · sem servidor real</span></section>`;}
function gradePage(){return top("Grade mensal","Setembro de 2026 · caminhão fictício DEM0A01")+`<section class="card"><h2>Inspeções de 21 a 26 de setembro</h2><div class="table-wrap"><table class="table-grade"><thead><tr><th>Item</th>${[21,22,23,24,25,26].map(d=>`<th>${d}/09</th>`).join("")}</tr></thead><tbody>${items.map(([title],i)=>`<tr><td>${title}</td>${[21,22,23,24,25,26].map(d=>{const s=d<=demoDay?effective(i+1,d):null;return `<td><span class="dot ${s==="ok"?"ok":s==="bad"?"bad":"na"}" title="${s==="ok"?"Conforme":s==="bad"?"Não conforme":"Sem registro"}">${s==="ok"?"✓":s==="bad"?"!":"—"}</span></td>`;}).join("")}</tr>`).join("")}</tbody></table></div><p class="footnote">✓ Conforme · ! Não conforme · — Sem registro. O domingo, dia 27, não faz parte da inspeção.</p><button data-action="print">Imprimir grade</button></section>`;}
function issuesPage(){return top("Não conformidades","Pendências fictícias acompanhadas até a resolução administrativa.")+Object.entries(issues).map(([id,issue])=>`<section class="card" style="margin-bottom:16px"><span class="status ${issue.open?"issue":"ok"}">${issue.open?"Pendente":"Resolvida"}</span><h2 style="margin-top:16px">${items[Number(id)-1][0]}</h2><p>Inspeção apontou necessidade de verificação.</p><p class="muted">Ocorrência fictícia · DEM0A01 · registrada em ${issue.openedDay}/09/2026 por Ana</p><div class="callout"><p>Exemplo de demonstração. Não representa defeito em qualquer veículo real.</p></div>${issue.open?(role==="admin"?`<button class="primary" data-action="resolve" data-id="${id}">Resolver ${items[Number(id)-1][0]}</button>`:`<p class="muted">Somente o administrador pode resolver esta pendência. Use o seletor de perfil para experimentar.</p>`):`<p class="muted">Resolução simulada pelo administrador em ${issue.resolvedDay}/09/2026.</p>`}</section>`).join("");}
function render(){const available=menus.filter(([key])=>key!=="relatorios"||role==="admin");if(!available.some(([key])=>key===view))view=available[0][0];app.innerHTML=`<div class="app ${isChecklist?"checklist":""}"><aside class="rail"><div class="brand"><span class="mark">✓</span>Operações<small>${isChecklist?"INSPEÇÃO DE FROTA":"GESTÃO"}</small></div><nav class="nav" aria-label="Menu principal">${available.map(([key,label])=>`<button data-action="navigate" data-view="${key}" ${view===key?'aria-current="page"':""}>${label}</button>`).join("")}</nav><div class="rail-note">Portfólio<br>Projeto demonstrativo<br><a href="https://github.com/santozbiel-hub/${isChecklist?"inspecao-frota-demo":"gestao-entregas-demo"}" target="_blank" rel="noopener noreferrer">Ver código no GitHub ↗</a></div></aside><main class="main"><header class="topbar"><span>DEMO / ${isChecklist?"CHECKLIST":"GESTÃO"}</span><label><span class="muted">Perfil de exemplo </span><select id="role" aria-label="Perfil de exemplo"><option value="admin" ${role==="admin"?"selected":""}>Administrador fictício</option><option value="employee" ${role!=="admin"?"selected":""}>${isChecklist?"Inspetora":"Funcionária"} fictícia</option></select></label></header><div class="demo-banner"><b>DEMONSTRAÇÃO</b> Todos os dados são fictícios. As alterações ficam apenas nesta página e desaparecem ao recarregar.</div>${isChecklist?(view==="hoje"?inspectionPage():view==="grade"?gradePage():issuesPage()):(view==="clientes"?clientsPage():view==="relatorios"?reportsPage():deliveryPage())}<footer class="footnote">Recorte interativo do projeto. Autenticação, fotos reais e sincronização de servidor não são executadas aqui. <button data-action="reset">Restaurar demonstração</button></footer></main></div>`;}
function details(id){const d=visibleDeliveries().find(row=>row.id===id);if(!d)return;openModal(escapeHtml(cname(d.client)),`<p class="muted">Entrega #${d.id} · ${d.date} · ${d.driver}</p><p>${badge(d)} · ${d.kind} · Cobrar em ${d.due}</p><div class="receipt"><b>NOTA DEMONSTRATIVA</b><p>SEM VALOR FISCAL</p><hr><dl><dt>Cliente fictício</dt><dd>${cname(d.client)}</dd><dt>Valor desta entrega</dt><dd>${money(d.cents)}</dd></dl><hr><small>Ilustração de comprovante. Nenhum documento real.</small></div><div class="actions">${!d.paid?`<button class="primary" data-action="pay" data-id="${d.id}">Simular pagamento</button>`:""}<button data-action="history" data-id="${d.client}">Histórico do cliente</button></div>`);}
function newDelivery(){openModal("Nova entrega fictícia",`<form id="new-delivery"><label>Cliente<select name="client">${clients.map(c=>`<option value="${c.id}">${c.name}</option>`).join("")}</select></label><label>Valor desta entrega (R$)<input name="amount" type="number" min="0.01" max="100000" step="0.01" value="130.00" required></label><label>Forma<select name="kind"><option>Boleto</option><option>À vista</option><option>Dívida</option></select></label><p class="muted">Registro simulado para Ana. Não informe dados reais.</p><button class="primary" type="submit">Adicionar à demonstração</button></form>`);}
document.addEventListener("click",event=>{const b=event.target.closest("button[data-action]");if(!b)return;const action=b.dataset.action,id=Number(b.dataset.id);switch(action){
case "navigate":view=b.dataset.view;query="";filter="todos";render();break;
case "close":modal.close();break;
case "details":details(id);break;
case "new":newDelivery();break;
case "pay":{const d=visibleDeliveries().find(row=>row.id===id);if(!d)return;d.paid=true;modal.close();render();notify("Pagamento fictício registrado somente nesta demonstração.");break;}
case "history":{if(modal.open)modal.close();openModal("Histórico do cliente",`<h3>${escapeHtml(cname(id))}</h3>${deliveryRows(visibleDeliveries().filter(d=>d.client===id))}`);break;}
case "mark":if(issues[id]?.open&&b.dataset.value==="ok")return;marks[demoDay]??={};marks[demoDay][id]=b.dataset.value;if(b.dataset.value==="bad"&&!issues[id]?.open)issues[id]={open:true,openedDay:demoDay,resolvedDay:null};if(offline)queued++;render();notify("Inspeção simulada atualizada.");break;
case "resolve":if(role!=="admin"||!issues[id]?.open)return;issues[id]={...issues[id],open:false,resolvedDay:demoDay};marks[demoDay]??={};marks[demoDay][id]="ok";render();notify("Pendência resolvida na demonstração.");break;
case "next-day":if(demoDay>=26){notify("A demonstração cobre de 21 a 26 de setembro. Use Restaurar para reiniciar.");return;}demoDay++;render();break;
case "offline":offline=!offline;if(!offline){queued=0;notify("Fila simulada esvaziada. Nenhum dado foi enviado.");}render();break;
case "print":window.print();break;
case "reset":deliveries=structuredClone(initialDeliveries);marks={21:{1:"ok",2:"ok",3:"ok",4:"bad",5:null}};issues={4:{open:true,openedDay:21,resolvedDay:null}};demoDay=21;offline=false;queued=0;query="";filter="todos";render();notify("Dados fictícios restaurados.");break;
}});
document.addEventListener("change",event=>{if(event.target.id==="role"){role=event.target.value;render();}if(event.target.id==="filter"){filter=event.target.value;document.getElementById("rows").innerHTML=deliveryRows(filteredRows());}});
document.addEventListener("input",event=>{if(event.target.id==="search"){query=event.target.value;document.getElementById("rows").innerHTML=deliveryRows(filteredRows());}});
document.addEventListener("submit",event=>{if(event.target.id!=="new-delivery")return;event.preventDefault();const data=new FormData(event.target),cents=Math.round(Number(data.get("amount"))*100),client=Number(data.get("client"));if(!Number.isSafeInteger(cents)||cents<=0||cents>10000000||!clients.some(c=>c.id===client))return;deliveries.unshift({id:Math.max(...deliveries.map(d=>d.id))+1,client,cents,driver:"Ana · fictícia",date:"21/09/2026",due:"22/09/2026",kind:String(data.get("kind")),paid:false});modal.close();render();notify("Entrega fictícia adicionada.");});
render();
// Navegação assistida opcional: usa exatamente o mesmo estado do menu visível.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:"navigate_demo",description:"Abre uma seção da demonstração fictícia, sem acesso à produção.",inputSchema:{type:"object",properties:{view:{type:"string",enum:menus.map(([id])=>id)}},required:["view"],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!menus.some(([id])=>id===input.view)||(input.view==="relatorios"&&role!=="admin"))throw new Error("Seção indisponível para o perfil atual.");view=input.view;render();return {view,demo:true};}})).catch(()=>{});}catch{}}
